name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --all-targets --all-features
    - name: Install cargo nextest
      run: cargo install cargo-nextest --locked
    - name: Run tests
      run: cargo nextest run --release
    - name: Generate doc
      run: RUSTDOCFLAGS="-D warnings" cargo doc --all-features --no-deps
    - name: Clippy
      run: cargo clippy --all-features --all-targets --tests -- -W clippy::all -D warnings
